//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADinfo
    {
        public int adid { get; set; }
        public string advertisename { get; set; }
        public string advertisetype { get; set; }
        public decimal advertisebudget { get; set; }
        public string contactno { get; set; }
    }
}
